name: Build and Deploy to Non-Production

on:
  push:
    branches:
      - qa
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'qa'
        type: choice
        options:
          - dev
          - qa

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: ${{ github.event.inputs.environment || 'qa' }}
      app-name: 'Git-webapp1'
      slot-name: ${{ github.event.inputs.environment || 'qa' }}
      artifact-name: ${{ needs.build.outputs.artifact_name }}
    secrets: inherit
