name: Build and Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'Production'
      app-name: 'Git-webapp3'
      slot-name: 'Production'
      artifact-name: ${{ build.outputs.artifact_name }}
    secrets: inherit
