name: Snyk Security Scan for .NET proj
on:
  push:
    branches:
      - master
jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
            
      - name: Install Snyk CLI
        run: |
          curl --compressed https://downloads.snyk.io/cli/stable/snyk-linux -o snyk
          chmod +x ./snyk
          sudo mv ./snyk /usr/local/bin/
          
      #- name: Authenticate Snyk
       # run: snyk auth ${{ secrets.SNYK_TOKEN }}
                
      - name: SnykWebUI report Security scan
        shell: bash
        if: '!cancelled()'
        continue-on-error: true
        run: |
          snyk code test --report --org="${{ secrets.SNYK_ORG }}" --detection-depth=10 --project-name="${{ github.event.repository.name }}" --target-name="${{ github.repository }}" 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG: ${{ secrets.SNYK_ORG }}
